/*
Apache JAMES Web Admin API

Testing RegexMappingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/searchlight/james-go-client"
)

func Test_openapi_RegexMappingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RegexMappingAPIService AddRegexMapping", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mappingSource string
		var regex string

		httpRes, err := apiClient.RegexMappingAPI.AddRegexMapping(context.Background(), mappingSource, regex).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegexMappingAPIService RemoveRegexMapping", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mappingSource string
		var regex string

		httpRes, err := apiClient.RegexMappingAPI.RemoveRegexMapping(context.Background(), mappingSource, regex).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
