/*
Apache JAMES Web Admin API

Testing AddressAliasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/searchlight/james-go-client"
)

func Test_openapi_AddressAliasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AddressAliasAPIService CreateAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userAddress string

		httpRes, err := apiClient.AddressAliasAPI.CreateAlias(context.Background(), userAddress).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressAliasAPIService DeleteAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userAddress string

		httpRes, err := apiClient.AddressAliasAPI.DeleteAlias(context.Background(), userAddress).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressAliasAPIService GetAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userAddress string

		resp, httpRes, err := apiClient.AddressAliasAPI.GetAlias(context.Background(), userAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressAliasAPIService ListAliases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AddressAliasAPI.ListAliases(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
