/*
Apache JAMES Web Admin API

Testing DeletedMessageVaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "go.opscenter.dev/james-go-client"
)

func Test_openapi_DeletedMessageVaultAPIService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeletedMessageVaultAPIService ExportDeletedMessages", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var user string

		httpRes, err := apiClient.DeletedMessageVaultAPI.ExportDeletedMessages(context.Background(), user).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeletedMessageVaultAPIService PurgeMessage", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var user string
		var messageId string

		httpRes, err := apiClient.DeletedMessageVaultAPI.PurgeMessage(context.Background(), user, messageId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeletedMessageVaultAPIService PurgeMessages", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.DeletedMessageVaultAPI.PurgeMessages(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeletedMessageVaultAPIService RestoreDeletedMessages", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var user string

		httpRes, err := apiClient.DeletedMessageVaultAPI.RestoreDeletedMessages(context.Background(), user).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
