/*
Apache JAMES Web Admin API

Testing AddressMappingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "go.opscenter.dev/james-go-client"
)

func Test_openapi_AddressMappingAPIService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AddressMappingAPIService AddAddressMapping", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var mappingSource string
		var destinationAddress string

		httpRes, err := apiClient.AddressMappingAPI.AddAddressMapping(context.Background(), mappingSource, destinationAddress).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test AddressMappingAPIService ListAddressMappings", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AddressMappingAPI.ListAddressMappings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test AddressMappingAPIService RemoveAddressMapping", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var mappingSource string
		var destinationAddress string

		httpRes, err := apiClient.AddressMappingAPI.RemoveAddressMapping(context.Background(), mappingSource, destinationAddress).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
