/*
Apache JAMES Web Admin API

Testing SieveQuotaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "go.opscenter.dev/james-go-client"
)

func Test_openapi_SieveQuotaAPIService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SieveQuotaAPIService GetUserSieveQuota", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var userEmail string

		httpRes, err := apiClient.SieveQuotaAPI.GetUserSieveQuota(context.Background(), userEmail).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SieveQuotaAPIService RemoveUserSieveQuota", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var userEmail string

		httpRes, err := apiClient.SieveQuotaAPI.RemoveUserSieveQuota(context.Background(), userEmail).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SieveQuotaAPIService SieveQuotaDefaultDelete", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SieveQuotaAPI.SieveQuotaDefaultDelete(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SieveQuotaAPIService SieveQuotaDefaultGet", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SieveQuotaAPI.SieveQuotaDefaultGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SieveQuotaAPIService UpdateGlobalSieveQuota", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SieveQuotaAPI.UpdateGlobalSieveQuota(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SieveQuotaAPIService UpdateUserSieveQuota", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var userEmail string

		httpRes, err := apiClient.SieveQuotaAPI.UpdateUserSieveQuota(context.Background(), userEmail).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
