/*
Apache JAMES Web Admin API

Testing MailRepositoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "go.opscenter.dev/james-go-client"
)

func Test_openapi_MailRepositoryAPIService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MailRepositoryAPIService CreateMailRepository", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var encodedPathOfTheRepository string

		httpRes, err := apiClient.MailRepositoryAPI.CreateMailRepository(context.Background(), encodedPathOfTheRepository).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test MailRepositoryAPIService GetMailRepository", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var encodedPathOfTheRepository string

		resp, httpRes, err := apiClient.MailRepositoryAPI.GetMailRepository(context.Background(), encodedPathOfTheRepository).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test MailRepositoryAPIService ListMailRepositories", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MailRepositoryAPI.ListMailRepositories(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test MailRepositoryAPIService ListMailsInMailRepository", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var encodedPathOfTheRepository string

		resp, httpRes, err := apiClient.MailRepositoryAPI.ListMailsInMailRepository(context.Background(), encodedPathOfTheRepository).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
