/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// MailboxAPIService MailboxAPI service
type MailboxAPIService service

type ApiPerformActionsOnMailboxesRequest struct {
	ctx context.Context
	ApiService *MailboxAPIService
	action *string
}

// Comma-separated list of actions to perform on mailboxes
func (r ApiPerformActionsOnMailboxesRequest) Action(action string) ApiPerformActionsOnMailboxesRequest {
	r.action = &action
	return r
}

func (r ApiPerformActionsOnMailboxesRequest) Execute() (*PerformActionsOnMailboxes201Response, *http.Response, error) {
	return r.ApiService.PerformActionsOnMailboxesExecute(r)
}

/*
PerformActionsOnMailboxes Perform actions on mailboxes

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPerformActionsOnMailboxesRequest
*/
func (a *MailboxAPIService) PerformActionsOnMailboxes(ctx context.Context) ApiPerformActionsOnMailboxesRequest {
	return ApiPerformActionsOnMailboxesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PerformActionsOnMailboxes201Response
func (a *MailboxAPIService) PerformActionsOnMailboxesExecute(r ApiPerformActionsOnMailboxesRequest) (*PerformActionsOnMailboxes201Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PerformActionsOnMailboxes201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MailboxAPIService.PerformActionsOnMailboxes")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mailboxes"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.action == nil {
		return localVarReturnValue, nil, reportError("action is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "action", r.action, "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiReindexMailboxRequest struct {
	ctx context.Context
	ApiService *MailboxAPIService
	mailboxId string
	task *string
	messagesPerSecond *int32
	mode *string
}

// The reindexing task to perform
func (r ApiReindexMailboxRequest) Task(task string) ApiReindexMailboxRequest {
	r.task = &task
	return r
}

// The rate at which messages should be processed per second
func (r ApiReindexMailboxRequest) MessagesPerSecond(messagesPerSecond int32) ApiReindexMailboxRequest {
	r.messagesPerSecond = &messagesPerSecond
	return r
}

// The reindexing mode used
func (r ApiReindexMailboxRequest) Mode(mode string) ApiReindexMailboxRequest {
	r.mode = &mode
	return r
}

func (r ApiReindexMailboxRequest) Execute() (*PerformActionsOnMailboxes201Response, *http.Response, error) {
	return r.ApiService.ReindexMailboxExecute(r)
}

/*
ReindexMailbox Reindex a mailbox

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param mailboxId ID of the mailbox to reindex
 @return ApiReindexMailboxRequest
*/
func (a *MailboxAPIService) ReindexMailbox(ctx context.Context, mailboxId string) ApiReindexMailboxRequest {
	return ApiReindexMailboxRequest{
		ApiService: a,
		ctx: ctx,
		mailboxId: mailboxId,
	}
}

// Execute executes the request
//  @return PerformActionsOnMailboxes201Response
func (a *MailboxAPIService) ReindexMailboxExecute(r ApiReindexMailboxRequest) (*PerformActionsOnMailboxes201Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PerformActionsOnMailboxes201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MailboxAPIService.ReindexMailbox")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/mailboxes/{mailboxId}"
	localVarPath = strings.Replace(localVarPath, "{"+"mailboxId"+"}", url.PathEscape(parameterValueToString(r.mailboxId, "mailboxId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.task == nil {
		return localVarReturnValue, nil, reportError("task is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "task", r.task, "")
	if r.messagesPerSecond != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "messagesPerSecond", r.messagesPerSecond, "")
	}
	if r.mode != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "mode", r.mode, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v Error
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
