/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListMailRepositories200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMailRepositories200ResponseInner{}

// ListMailRepositories200ResponseInner struct for ListMailRepositories200ResponseInner
type ListMailRepositories200ResponseInner struct {
	Path *string `json:"path,omitempty"`
	Repository *string `json:"repository,omitempty"`
}

// NewListMailRepositories200ResponseInner instantiates a new ListMailRepositories200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMailRepositories200ResponseInner() *ListMailRepositories200ResponseInner {
	this := ListMailRepositories200ResponseInner{}
	return &this
}

// NewListMailRepositories200ResponseInnerWithDefaults instantiates a new ListMailRepositories200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMailRepositories200ResponseInnerWithDefaults() *ListMailRepositories200ResponseInner {
	this := ListMailRepositories200ResponseInner{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ListMailRepositories200ResponseInner) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMailRepositories200ResponseInner) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ListMailRepositories200ResponseInner) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ListMailRepositories200ResponseInner) SetPath(v string) {
	o.Path = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *ListMailRepositories200ResponseInner) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMailRepositories200ResponseInner) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *ListMailRepositories200ResponseInner) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *ListMailRepositories200ResponseInner) SetRepository(v string) {
	o.Repository = &v
}

func (o ListMailRepositories200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMailRepositories200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	return toSerialize, nil
}

type NullableListMailRepositories200ResponseInner struct {
	value *ListMailRepositories200ResponseInner
	isSet bool
}

func (v NullableListMailRepositories200ResponseInner) Get() *ListMailRepositories200ResponseInner {
	return v.value
}

func (v *NullableListMailRepositories200ResponseInner) Set(val *ListMailRepositories200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListMailRepositories200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListMailRepositories200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMailRepositories200ResponseInner(val *ListMailRepositories200ResponseInner) *NullableListMailRepositories200ResponseInner {
	return &NullableListMailRepositories200ResponseInner{value: val, isSet: true}
}

func (v NullableListMailRepositories200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMailRepositories200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


