/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateUserIdentityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserIdentityRequest{}

// UpdateUserIdentityRequest struct for UpdateUserIdentityRequest
type UpdateUserIdentityRequest struct {
	Bcc []ListUserIdentities200ResponseInnerBccInner `json:"bcc,omitempty"`
	HtmlSignature *string `json:"htmlSignature,omitempty"`
	Name *string `json:"name,omitempty"`
	ReplyTo []ListUserIdentities200ResponseInnerBccInner `json:"replyTo,omitempty"`
	SortOrder *int32 `json:"sortOrder,omitempty"`
	TextSignature *string `json:"textSignature,omitempty"`
}

// NewUpdateUserIdentityRequest instantiates a new UpdateUserIdentityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserIdentityRequest() *UpdateUserIdentityRequest {
	this := UpdateUserIdentityRequest{}
	return &this
}

// NewUpdateUserIdentityRequestWithDefaults instantiates a new UpdateUserIdentityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserIdentityRequestWithDefaults() *UpdateUserIdentityRequest {
	this := UpdateUserIdentityRequest{}
	return &this
}

// GetBcc returns the Bcc field value if set, zero value otherwise.
func (o *UpdateUserIdentityRequest) GetBcc() []ListUserIdentities200ResponseInnerBccInner {
	if o == nil || IsNil(o.Bcc) {
		var ret []ListUserIdentities200ResponseInnerBccInner
		return ret
	}
	return o.Bcc
}

// GetBccOk returns a tuple with the Bcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserIdentityRequest) GetBccOk() ([]ListUserIdentities200ResponseInnerBccInner, bool) {
	if o == nil || IsNil(o.Bcc) {
		return nil, false
	}
	return o.Bcc, true
}

// HasBcc returns a boolean if a field has been set.
func (o *UpdateUserIdentityRequest) HasBcc() bool {
	if o != nil && !IsNil(o.Bcc) {
		return true
	}

	return false
}

// SetBcc gets a reference to the given []ListUserIdentities200ResponseInnerBccInner and assigns it to the Bcc field.
func (o *UpdateUserIdentityRequest) SetBcc(v []ListUserIdentities200ResponseInnerBccInner) {
	o.Bcc = v
}

// GetHtmlSignature returns the HtmlSignature field value if set, zero value otherwise.
func (o *UpdateUserIdentityRequest) GetHtmlSignature() string {
	if o == nil || IsNil(o.HtmlSignature) {
		var ret string
		return ret
	}
	return *o.HtmlSignature
}

// GetHtmlSignatureOk returns a tuple with the HtmlSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserIdentityRequest) GetHtmlSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlSignature) {
		return nil, false
	}
	return o.HtmlSignature, true
}

// HasHtmlSignature returns a boolean if a field has been set.
func (o *UpdateUserIdentityRequest) HasHtmlSignature() bool {
	if o != nil && !IsNil(o.HtmlSignature) {
		return true
	}

	return false
}

// SetHtmlSignature gets a reference to the given string and assigns it to the HtmlSignature field.
func (o *UpdateUserIdentityRequest) SetHtmlSignature(v string) {
	o.HtmlSignature = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateUserIdentityRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserIdentityRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateUserIdentityRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateUserIdentityRequest) SetName(v string) {
	o.Name = &v
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise.
func (o *UpdateUserIdentityRequest) GetReplyTo() []ListUserIdentities200ResponseInnerBccInner {
	if o == nil || IsNil(o.ReplyTo) {
		var ret []ListUserIdentities200ResponseInnerBccInner
		return ret
	}
	return o.ReplyTo
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserIdentityRequest) GetReplyToOk() ([]ListUserIdentities200ResponseInnerBccInner, bool) {
	if o == nil || IsNil(o.ReplyTo) {
		return nil, false
	}
	return o.ReplyTo, true
}

// HasReplyTo returns a boolean if a field has been set.
func (o *UpdateUserIdentityRequest) HasReplyTo() bool {
	if o != nil && !IsNil(o.ReplyTo) {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given []ListUserIdentities200ResponseInnerBccInner and assigns it to the ReplyTo field.
func (o *UpdateUserIdentityRequest) SetReplyTo(v []ListUserIdentities200ResponseInnerBccInner) {
	o.ReplyTo = v
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise.
func (o *UpdateUserIdentityRequest) GetSortOrder() int32 {
	if o == nil || IsNil(o.SortOrder) {
		var ret int32
		return ret
	}
	return *o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserIdentityRequest) GetSortOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.SortOrder) {
		return nil, false
	}
	return o.SortOrder, true
}

// HasSortOrder returns a boolean if a field has been set.
func (o *UpdateUserIdentityRequest) HasSortOrder() bool {
	if o != nil && !IsNil(o.SortOrder) {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given int32 and assigns it to the SortOrder field.
func (o *UpdateUserIdentityRequest) SetSortOrder(v int32) {
	o.SortOrder = &v
}

// GetTextSignature returns the TextSignature field value if set, zero value otherwise.
func (o *UpdateUserIdentityRequest) GetTextSignature() string {
	if o == nil || IsNil(o.TextSignature) {
		var ret string
		return ret
	}
	return *o.TextSignature
}

// GetTextSignatureOk returns a tuple with the TextSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserIdentityRequest) GetTextSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.TextSignature) {
		return nil, false
	}
	return o.TextSignature, true
}

// HasTextSignature returns a boolean if a field has been set.
func (o *UpdateUserIdentityRequest) HasTextSignature() bool {
	if o != nil && !IsNil(o.TextSignature) {
		return true
	}

	return false
}

// SetTextSignature gets a reference to the given string and assigns it to the TextSignature field.
func (o *UpdateUserIdentityRequest) SetTextSignature(v string) {
	o.TextSignature = &v
}

func (o UpdateUserIdentityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserIdentityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bcc) {
		toSerialize["bcc"] = o.Bcc
	}
	if !IsNil(o.HtmlSignature) {
		toSerialize["htmlSignature"] = o.HtmlSignature
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ReplyTo) {
		toSerialize["replyTo"] = o.ReplyTo
	}
	if !IsNil(o.SortOrder) {
		toSerialize["sortOrder"] = o.SortOrder
	}
	if !IsNil(o.TextSignature) {
		toSerialize["textSignature"] = o.TextSignature
	}
	return toSerialize, nil
}

type NullableUpdateUserIdentityRequest struct {
	value *UpdateUserIdentityRequest
	isSet bool
}

func (v NullableUpdateUserIdentityRequest) Get() *UpdateUserIdentityRequest {
	return v.value
}

func (v *NullableUpdateUserIdentityRequest) Set(val *UpdateUserIdentityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserIdentityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserIdentityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserIdentityRequest(val *UpdateUserIdentityRequest) *NullableUpdateUserIdentityRequest {
	return &NullableUpdateUserIdentityRequest{value: val, isSet: true}
}

func (v NullableUpdateUserIdentityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserIdentityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


