/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAlias200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAlias200ResponseInner{}

// GetAlias200ResponseInner struct for GetAlias200ResponseInner
type GetAlias200ResponseInner struct {
	Source *string `json:"source,omitempty"`
}

// NewGetAlias200ResponseInner instantiates a new GetAlias200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAlias200ResponseInner() *GetAlias200ResponseInner {
	this := GetAlias200ResponseInner{}
	return &this
}

// NewGetAlias200ResponseInnerWithDefaults instantiates a new GetAlias200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAlias200ResponseInnerWithDefaults() *GetAlias200ResponseInner {
	this := GetAlias200ResponseInner{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *GetAlias200ResponseInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAlias200ResponseInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *GetAlias200ResponseInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *GetAlias200ResponseInner) SetSource(v string) {
	o.Source = &v
}

func (o GetAlias200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAlias200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableGetAlias200ResponseInner struct {
	value *GetAlias200ResponseInner
	isSet bool
}

func (v NullableGetAlias200ResponseInner) Get() *GetAlias200ResponseInner {
	return v.value
}

func (v *NullableGetAlias200ResponseInner) Set(val *GetAlias200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAlias200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAlias200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAlias200ResponseInner(val *GetAlias200ResponseInner) *NullableGetAlias200ResponseInner {
	return &NullableGetAlias200ResponseInner{value: val, isSet: true}
}

func (v NullableGetAlias200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAlias200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


