/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpgradeToLatestSchemaVersion200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeToLatestSchemaVersion200Response{}

// UpgradeToLatestSchemaVersion200Response struct for UpgradeToLatestSchemaVersion200Response
type UpgradeToLatestSchemaVersion200Response struct {
	AdditionalInformation *UpgradeToLatestSchemaVersion200ResponseAdditionalInformation `json:"additionalInformation,omitempty"`
	TaskId *string `json:"taskId,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewUpgradeToLatestSchemaVersion200Response instantiates a new UpgradeToLatestSchemaVersion200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeToLatestSchemaVersion200Response() *UpgradeToLatestSchemaVersion200Response {
	this := UpgradeToLatestSchemaVersion200Response{}
	return &this
}

// NewUpgradeToLatestSchemaVersion200ResponseWithDefaults instantiates a new UpgradeToLatestSchemaVersion200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeToLatestSchemaVersion200ResponseWithDefaults() *UpgradeToLatestSchemaVersion200Response {
	this := UpgradeToLatestSchemaVersion200Response{}
	return &this
}

// GetAdditionalInformation returns the AdditionalInformation field value if set, zero value otherwise.
func (o *UpgradeToLatestSchemaVersion200Response) GetAdditionalInformation() UpgradeToLatestSchemaVersion200ResponseAdditionalInformation {
	if o == nil || IsNil(o.AdditionalInformation) {
		var ret UpgradeToLatestSchemaVersion200ResponseAdditionalInformation
		return ret
	}
	return *o.AdditionalInformation
}

// GetAdditionalInformationOk returns a tuple with the AdditionalInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeToLatestSchemaVersion200Response) GetAdditionalInformationOk() (*UpgradeToLatestSchemaVersion200ResponseAdditionalInformation, bool) {
	if o == nil || IsNil(o.AdditionalInformation) {
		return nil, false
	}
	return o.AdditionalInformation, true
}

// HasAdditionalInformation returns a boolean if a field has been set.
func (o *UpgradeToLatestSchemaVersion200Response) HasAdditionalInformation() bool {
	if o != nil && !IsNil(o.AdditionalInformation) {
		return true
	}

	return false
}

// SetAdditionalInformation gets a reference to the given UpgradeToLatestSchemaVersion200ResponseAdditionalInformation and assigns it to the AdditionalInformation field.
func (o *UpgradeToLatestSchemaVersion200Response) SetAdditionalInformation(v UpgradeToLatestSchemaVersion200ResponseAdditionalInformation) {
	o.AdditionalInformation = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *UpgradeToLatestSchemaVersion200Response) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeToLatestSchemaVersion200Response) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *UpgradeToLatestSchemaVersion200Response) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *UpgradeToLatestSchemaVersion200Response) SetTaskId(v string) {
	o.TaskId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UpgradeToLatestSchemaVersion200Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeToLatestSchemaVersion200Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UpgradeToLatestSchemaVersion200Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UpgradeToLatestSchemaVersion200Response) SetType(v string) {
	o.Type = &v
}

func (o UpgradeToLatestSchemaVersion200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeToLatestSchemaVersion200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalInformation) {
		toSerialize["additionalInformation"] = o.AdditionalInformation
	}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableUpgradeToLatestSchemaVersion200Response struct {
	value *UpgradeToLatestSchemaVersion200Response
	isSet bool
}

func (v NullableUpgradeToLatestSchemaVersion200Response) Get() *UpgradeToLatestSchemaVersion200Response {
	return v.value
}

func (v *NullableUpgradeToLatestSchemaVersion200Response) Set(val *UpgradeToLatestSchemaVersion200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeToLatestSchemaVersion200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeToLatestSchemaVersion200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeToLatestSchemaVersion200Response(val *UpgradeToLatestSchemaVersion200Response) *NullableUpgradeToLatestSchemaVersion200Response {
	return &NullableUpgradeToLatestSchemaVersion200Response{value: val, isSet: true}
}

func (v NullableUpgradeToLatestSchemaVersion200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeToLatestSchemaVersion200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


