/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ListMailsOfMailQueue200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMailsOfMailQueue200ResponseInner{}

// ListMailsOfMailQueue200ResponseInner struct for ListMailsOfMailQueue200ResponseInner
type ListMailsOfMailQueue200ResponseInner struct {
	Name *string `json:"name,omitempty"`
	NextDelivery *time.Time `json:"nextDelivery,omitempty"`
	Recipients []string `json:"recipients,omitempty"`
	Sender *string `json:"sender,omitempty"`
}

// NewListMailsOfMailQueue200ResponseInner instantiates a new ListMailsOfMailQueue200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMailsOfMailQueue200ResponseInner() *ListMailsOfMailQueue200ResponseInner {
	this := ListMailsOfMailQueue200ResponseInner{}
	return &this
}

// NewListMailsOfMailQueue200ResponseInnerWithDefaults instantiates a new ListMailsOfMailQueue200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMailsOfMailQueue200ResponseInnerWithDefaults() *ListMailsOfMailQueue200ResponseInner {
	this := ListMailsOfMailQueue200ResponseInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListMailsOfMailQueue200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMailsOfMailQueue200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListMailsOfMailQueue200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListMailsOfMailQueue200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetNextDelivery returns the NextDelivery field value if set, zero value otherwise.
func (o *ListMailsOfMailQueue200ResponseInner) GetNextDelivery() time.Time {
	if o == nil || IsNil(o.NextDelivery) {
		var ret time.Time
		return ret
	}
	return *o.NextDelivery
}

// GetNextDeliveryOk returns a tuple with the NextDelivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMailsOfMailQueue200ResponseInner) GetNextDeliveryOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextDelivery) {
		return nil, false
	}
	return o.NextDelivery, true
}

// HasNextDelivery returns a boolean if a field has been set.
func (o *ListMailsOfMailQueue200ResponseInner) HasNextDelivery() bool {
	if o != nil && !IsNil(o.NextDelivery) {
		return true
	}

	return false
}

// SetNextDelivery gets a reference to the given time.Time and assigns it to the NextDelivery field.
func (o *ListMailsOfMailQueue200ResponseInner) SetNextDelivery(v time.Time) {
	o.NextDelivery = &v
}

// GetRecipients returns the Recipients field value if set, zero value otherwise.
func (o *ListMailsOfMailQueue200ResponseInner) GetRecipients() []string {
	if o == nil || IsNil(o.Recipients) {
		var ret []string
		return ret
	}
	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMailsOfMailQueue200ResponseInner) GetRecipientsOk() ([]string, bool) {
	if o == nil || IsNil(o.Recipients) {
		return nil, false
	}
	return o.Recipients, true
}

// HasRecipients returns a boolean if a field has been set.
func (o *ListMailsOfMailQueue200ResponseInner) HasRecipients() bool {
	if o != nil && !IsNil(o.Recipients) {
		return true
	}

	return false
}

// SetRecipients gets a reference to the given []string and assigns it to the Recipients field.
func (o *ListMailsOfMailQueue200ResponseInner) SetRecipients(v []string) {
	o.Recipients = v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *ListMailsOfMailQueue200ResponseInner) GetSender() string {
	if o == nil || IsNil(o.Sender) {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMailsOfMailQueue200ResponseInner) GetSenderOk() (*string, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *ListMailsOfMailQueue200ResponseInner) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *ListMailsOfMailQueue200ResponseInner) SetSender(v string) {
	o.Sender = &v
}

func (o ListMailsOfMailQueue200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMailsOfMailQueue200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NextDelivery) {
		toSerialize["nextDelivery"] = o.NextDelivery
	}
	if !IsNil(o.Recipients) {
		toSerialize["recipients"] = o.Recipients
	}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	return toSerialize, nil
}

type NullableListMailsOfMailQueue200ResponseInner struct {
	value *ListMailsOfMailQueue200ResponseInner
	isSet bool
}

func (v NullableListMailsOfMailQueue200ResponseInner) Get() *ListMailsOfMailQueue200ResponseInner {
	return v.value
}

func (v *NullableListMailsOfMailQueue200ResponseInner) Set(val *ListMailsOfMailQueue200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListMailsOfMailQueue200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListMailsOfMailQueue200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMailsOfMailQueue200ResponseInner(val *ListMailsOfMailQueue200ResponseInner) *NullableListMailsOfMailQueue200ResponseInner {
	return &NullableListMailsOfMailQueue200ResponseInner{value: val, isSet: true}
}

func (v NullableListMailsOfMailQueue200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMailsOfMailQueue200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


