/*
Apache JAMES Web Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CleanUploadRepository201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CleanUploadRepository201Response{}

// CleanUploadRepository201Response struct for CleanUploadRepository201Response
type CleanUploadRepository201Response struct {
	// Identifier of the scheduled task
	TaskId *string `json:"taskId,omitempty"`
}

// NewCleanUploadRepository201Response instantiates a new CleanUploadRepository201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCleanUploadRepository201Response() *CleanUploadRepository201Response {
	this := CleanUploadRepository201Response{}
	return &this
}

// NewCleanUploadRepository201ResponseWithDefaults instantiates a new CleanUploadRepository201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCleanUploadRepository201ResponseWithDefaults() *CleanUploadRepository201Response {
	this := CleanUploadRepository201Response{}
	return &this
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *CleanUploadRepository201Response) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CleanUploadRepository201Response) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *CleanUploadRepository201Response) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *CleanUploadRepository201Response) SetTaskId(v string) {
	o.TaskId = &v
}

func (o CleanUploadRepository201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CleanUploadRepository201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	return toSerialize, nil
}

type NullableCleanUploadRepository201Response struct {
	value *CleanUploadRepository201Response
	isSet bool
}

func (v NullableCleanUploadRepository201Response) Get() *CleanUploadRepository201Response {
	return v.value
}

func (v *NullableCleanUploadRepository201Response) Set(val *CleanUploadRepository201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCleanUploadRepository201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCleanUploadRepository201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCleanUploadRepository201Response(val *CleanUploadRepository201Response) *NullableCleanUploadRepository201Response {
	return &NullableCleanUploadRepository201Response{value: val, isSet: true}
}

func (v NullableCleanUploadRepository201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCleanUploadRepository201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


